/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.login.register;

/**
 *
 * @author mayank
 */
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Supervisor_form extends javax.swing.JFrame {

    /**
     * Creates new form Supervisor_form
     */
    public Supervisor_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_U = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_UN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField_PASS = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField_REPSS = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_EID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_DEP = new javax.swing.JComboBox();
        jButton_Register_ = new javax.swing.JButton();
        jButton_CANCEL = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Retype Password:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 38, 19));

        jLabelClose.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("for Supervisors");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setText("REGISTRATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(245, 229, 27));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Password:");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("Retype Password:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Employee id:");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Department:");

        jComboBox_DEP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science Engineering", "Mechanical Engineering", "Electronics & Communication Engineering", "Electrical Engineering", "Civil Engineering", "Instrumentation & Control Engineering", "Chemical Engineering" }));
        jComboBox_DEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DEPActionPerformed(evt);
            }
        });

        jButton_Register_.setBackground(new java.awt.Color(0, 230, 64));
        jButton_Register_.setText("Register");
        jButton_Register_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Register_MouseClicked(evt);
            }
        });
        jButton_Register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Register_ActionPerformed(evt);
            }
        });

        jButton_CANCEL.setBackground(new java.awt.Color(0, 181, 204));
        jButton_CANCEL.setText("Cancel");
        jButton_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CANCELActionPerformed(evt);
            }
        });

        jLabel6.setText("Click here to login for Supervisors");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField_REPSS, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_U)
                        .addComponent(jTextField_UN)
                        .addComponent(jPasswordField_PASS, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                    .addComponent(jTextField_EID, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_DEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton_Register_, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(229, 229, 229))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_UN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPasswordField_PASS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField_REPSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_EID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox_DEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Register_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jComboBox_DEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DEPActionPerformed

    private void jButton_Register_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Register_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Register_MouseClicked

    private void jButton_Register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Register_ActionPerformed
        String name=jTextField_U.getText();
        String uname=jTextField_UN.getText();
        String pass=String.valueOf(jPasswordField_PASS.getPassword());
        String re_pass=String.valueOf(jPasswordField_REPSS.getPassword());
        String e_id=jTextField_EID.getText();
        String dep=jComboBox_DEP.getSelectedItem().toString();
        
        if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a Username");
        }

        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a Password");
        }

        else if(!pass.equals(re_pass))
        {
            JOptionPane.showMessageDialog(null, "Retype Password Again!!");
        }

        else if(checkUsername(uname))
        {
            JOptionPane.showMessageDialog(null, "This Username is already registered");
        }

        else
        {
            PreparedStatement ps3,ps4,ps5;
            ResultSet rs,rs1;
            String query="INSERT INTO `Supervisor_registrations`(`name`, `uname`, `password`, `department`, `e_id`) VALUES (?,?,?,?,?)";
            String query1="SELECT * FROM `Supervisor_registrations`";
            String query2="INSERT INTO `Supervisor_Allocation`(`e_id`, `department`, `block`, `Day1`, `Day2`, `Day3`, `Day4`, `Day5`) VALUES (?,?,?,?,?,?,?,?)";
            try {
                ps3=MyConnection.getConnection().prepareStatement(query);
                ps4=MyConnection.getConnection().prepareStatement(query1);
                ps5=MyConnection.getConnection().prepareStatement(query2);
                ps3.setString(1, name);
                ps3.setString(2, uname);
                ps3.setString(3, pass);
                ps3.setString(5, e_id);
                ps3.setString(4, dep);
                
                int fc=0;
                rs=ps4.executeQuery();
                while(rs.next())
                {
                    if(dep.equals(rs.getString(6)))
                        fc++;
                }
                /*if(ps3.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "Thank You For Registration, Respected!!");
                }*/
                String department=dep;
                
                if("Computer Science Engineering".equals(department) && fc>29)
                    JOptionPane.showMessageDialog(null, "Sorry Respected!! Registrations are closed for this BRANCH");
                
                else if(("Mechanical Engineering".equals(department) || "Electrical Engineering".equals(department) || "Instrumentation & Control Engineering".equals(department) || "Electronics & Communication Engineering".equals(department) || "Civil Engineering".equals(department) || "Chemical Engineering".equals(department)) && fc>14)
                    JOptionPane.showMessageDialog(null, "Sorry Respected!! Registrations are closed for this BRANCH");
                
                else
                {
                    ps3.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Thank You For Registration, Respected!!");
                    String block="";
                if("Computer Science Engineering".equals(department))
			block="A";
		else if("Mechanical Engineering".equals(department) || "Electronics & Communication Engineering".equals(department))
			block="B";
		else if("Electrical Engineering".equals(department) || "Civil Engineering".equals(department))
			block="C";
		else if("Instrumentation & Control Engineering".equals(department) || "Chemical Engineering".equals(department))
			block="D";
		int n=fc+1;
		char d[][]=new char[5][3];
		for(int i=0;i<5;i++)
			d[i][1]='0';
		if("Computer Science Engineering".equals(department))
		{
			if(n<=10)
			{
				for(int i=0;i<5;i++)
					d[i][0]='1';
			}
			else if(n>10 && n<=20)
			{	for(int i=0;i<5;i++)
					d[i][0]='2';
			}
			else if(n>20 && n<=30)
			{	for(int i=0;i<5;i++)
					d[i][0]='3';
			}
			if(n%10==1)
			{
				d[0][2]='1';
				d[1][2]='2';
				d[2][2]='3';
				d[3][2]='4';
				d[4][0]='o';
				d[4][1]=d[4][2]='f';
			}
			else if(n%10==2)
			{
				d[0][0]='o';
				d[0][1]=d[0][2]='f';
				d[1][2]='1';
				d[2][2]='2';
				d[3][2]='3';
				d[4][2]='4';
			}
			else if(n%10==3)
			{
				d[0][2]='4';
				d[1][0]='o';
				d[1][1]=d[1][2]='f';
				d[2][2]='1';
				d[3][2]='2';
				d[4][2]='3';
			}
			else if(n%10==4)
			{
				d[0][2]='3';
				d[1][2]='4';
				d[2][0]='o';
				d[2][1]=d[2][2]='f';
				d[3][2]='1';
				d[4][2]='2';
			}
			else if(n%10==5)
			{
				d[0][2]='2';
				d[1][2]='3';
				d[2][2]='4';
				d[3][0]='o';
				d[3][1]=d[3][2]='f';
				d[4][2]='1';
			}
			else if(n%10==6)
			{
				d[0][2]='1'+4;
				d[1][2]='2'+4;
				d[2][2]='3'+4;
				d[3][2]='4'+4;
				d[4][0]='o';
				d[4][1]=d[4][2]='f';
			}
			else if(n%10==7)
			{
				d[0][0]='o';
				d[0][1]=d[0][2]='f';
				d[1][2]='1'+4;
				d[2][2]='2'+4;
				d[3][2]='3'+4;
				d[4][2]='4'+4;
			}
			else if(n%10==8)
			{
				d[0][2]='4'+4;
				d[1][0]='o';
				d[1][1]=d[1][2]='f';
				d[2][2]='1'+4;
				d[3][2]='2'+4;
				d[4][2]='3'+4;
			}
			else if(n%10==9)
			{
				d[0][2]='3'+4;
				d[1][2]='4'+4;
				d[2][0]='o';
				d[2][1]=d[2][2]='f';
				d[3][2]='1'+4;
				d[4][2]='2'+4;
			}
			else if(n%10==0)
			{
				d[0][2]='2'+4;
				d[1][2]='3'+4;
				d[2][2]='4'+4;
				d[3][0]='o';
				d[3][1]=d[3][2]='f';
				d[4][2]='1'+4;
			}
		}
		else if("Mechanical Engineering".equals(department) || "Electrical Engineering".equals(department) || "Instrumentation & Control Engineering".equals(department))
		{
			if(n<=5)
			{
				for(int i=0;i<5;i++)
					d[i][0]='1';
			}
			else if(n>5 && n<=10)
			{	for(int i=0;i<5;i++)
					d[i][0]='2';
			}
			else if(n>10 && n<=15)
			{	for(int i=0;i<5;i++)
					d[i][0]='3';
			}
			if(n%5==1)
			{
				d[0][2]='1';
				d[1][2]='2';
				d[2][2]='3';
				d[3][2]='4';
				d[4][0]='o';
				d[4][1]=d[4][2]='f';
			}
			else if(n%5==2)
			{
				d[0][0]='o';
				d[0][1]=d[0][2]='f';
				d[1][2]='1';
				d[2][2]='2';
				d[3][2]='3';
				d[4][2]='4';
			}
			else if(n%5==3)
			{
				d[0][2]='4';
				d[1][0]='o';
				d[1][1]=d[1][2]='f';
				d[2][2]='1';
				d[3][2]='2';
				d[4][2]='3';
			}
			else if(n%5==4)
			{
				d[0][2]='3';
				d[1][2]='4';
				d[2][0]='o';
				d[2][1]=d[2][2]='f';
				d[3][2]='1';
				d[4][2]='2';
			}
			else if(n%5==0)
			{
				d[0][2]='2';
				d[1][2]='3';
				d[2][2]='4';
				d[3][0]='o';
				d[3][1]=d[3][2]='f';
				d[4][2]='1';
			}
		}
		else if("Electronics & Communication Engineering".equals(department) || "Civil Engineering".equals(department) || "Chemical Engineering".equals(department))
		{
			if(n<=5)
			{
				for(int i=0;i<5;i++)
					d[i][0]='1';
			}
			else if(n>5 && n<=10)
			{	for(int i=0;i<5;i++)
					d[i][0]='2';
			}
			else if(n>10 && n<=15)
			{	for(int i=0;i<5;i++)
					d[i][0]='3';
			}
			if(n%5==1)
			{
				d[0][2]='1'+4;
				d[1][2]='2'+4;
				d[2][2]='3'+4;
				d[3][2]='4'+4;
				d[4][0]='o';
				d[4][1]=d[4][2]='f';
			}
			else if(n%5==2)
			{
				d[0][0]='o';
				d[0][1]=d[0][2]='f';
				d[1][2]='1'+4;
				d[2][2]='2'+4;
				d[3][2]='3'+4;
				d[4][2]='4'+4;
			}
			else if(n%5==3)
			{
				d[0][2]='4'+4;
				d[1][0]='o';
				d[1][1]=d[1][2]='f';
				d[2][2]='1'+4;
				d[3][2]='2'+4;
				d[4][2]='3'+4;
			}
			else if(n%5==4)
			{
				d[0][2]='3'+4;
				d[1][2]='4'+4;
				d[2][0]='o';
				d[2][1]=d[2][2]='f';
				d[3][2]='1'+4;
				d[4][2]='2'+4;
			}
			else if(n%5==0)
			{
				d[0][2]='2'+4;
				d[1][2]='3'+4;
				d[2][2]='4'+4;
				d[3][0]='o';
				d[3][1]=d[3][2]='f';
				d[4][2]='1'+4;
			}
		}
		String D1=new String(d[0]);
                String D2=new String(d[1]);
                String D3=new String(d[2]);
                String D4=new String(d[3]);
                String D5=new String(d[4]);
                ps5.setString(1, e_id);
                ps5.setString(2, dep);
                ps5.setString(3, block);
                ps5.setString(4, D1);
                ps5.setString(5, D2);
                ps5.setString(6, D3);
                ps5.setString(7, D4);
                ps5.setString(8, D5);
                fc=0;
                ps5.executeUpdate();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_Register_ActionPerformed

    private void jButton_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CANCELActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_CANCELActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Supervisorreg svg=new Supervisorreg();
        svg.setVisible(true);
        svg.pack();
        svg.setLocationRelativeTo(null);
        svg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked
    public boolean checkUsername(String username)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser=false;
        
        
        String query="SELECT * FROM `Supervisor_registrations` WHERE `uname`=?";
        
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, username);
            
            rs=ps.executeQuery();
            
            if(rs.next())
            {
                checkUser=true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkUser;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supervisor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supervisor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supervisor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supervisor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supervisor_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CANCEL;
    private javax.swing.JButton jButton_Register_;
    private javax.swing.JComboBox jComboBox_DEP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_PASS;
    private javax.swing.JPasswordField jPasswordField_REPSS;
    private javax.swing.JTextField jTextField_EID;
    private javax.swing.JTextField jTextField_U;
    private javax.swing.JTextField jTextField_UN;
    // End of variables declaration//GEN-END:variables
}
